## Test

In [ ]:
import os
import sys
import pandas as pd

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), os.pardir, "quant_wealth_partner")))

from utilities.stocks.fetch_india_stocks import nse_fetch_data

In [15]:
out1 = nse_fetch_data("/api/NextApi/apiClient/marketWatchApi?functionName=getIndicesData&symbol=NIFTY%2050")
df1 = pd.DataFrame(out1.get("data", {}).get("data", []))  #marketStatus, #aduCount
df1.head(5)

,priority,identifier,change,symbol,series,marketType,lastPrice,totalTradedVolume,open,dayHigh,...,perChange365d,perChange30d,date365dAgo,date30dAgo,nearWKH,nearWKL,chart30Path,chart365Path,companyName,pChange
0,1,NIFTY 50,4.10,NIFTY 50,NaN,NaN,24211.0,322678968,24039.4,24259.80,...,-3.73,2.49,11-Jul-2025,12-Jun-2026,8.198474,-9.144350,,,NaN,0.02
1,0,TCSEQN,113.90,TCS,EQ,N,2182.9,12382622,2075.0,2204.90,...,-33.16,0.99,11-Jul-2025,12-Jun-2026,35.778170,-10.425941,NaN,NaN,TATA CONSULTANCY SERVICES LIMITED,5.51
2,0,INFYEQN,34.60,INFY,EQ,N,1102.6,20994760,1057.1,1114.90,...,-30.87,-1.24,11-Jul-2025,12-Jun-2026,36.192130,-12.235342,NaN,NaN,INFOSYS LIMITED,3.24
3,0,HDFCBANKEQN,-7.45,HDFCBANK,EQ,N,817.5,21741736,817.0,821.95,...,-17.58,5.83,11-Jul-2025,12-Jun-2026,19.892210,-12.502580,NaN,NaN,HDFC BANK LIMITED,-0.90
4,0,BHARTIARTLEQN,-16.80,BHARTIARTL,EQ,N,1903.6,7862506,1914.0,1917.00,...,-0.95,4.45,11-Jul-2025,12-Jun-2026,12.458036,-9.370870,NaN,NaN,BHARTI AIRTEL LIMITED,-0.87

In [17]:
out2 = nse_fetch_data("/api/NextApi/apiClient/indexTrackerApi?functionName=getIndicesHeatMap&&index=NIFTY%2050")
df2 = pd.DataFrame(out2.get("data", []))
df2.head(5)

2026-07-13 22:18:22.358 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Successfully fetched data from https://www.nseindia.com/api/NextApi/apiClient/indexTrackerApi?functionName=getIndicesHeatMap&&index=NIFTY%2050

,VWAP,change,high,identifier,lastPrice,low,marketType,pchange,series,symbol,tradedValue,tradedVolume,vWAP
0,2162.89,113.9,2204.9,TCSEQN,2182.9,2065.1,N,5.51,EQ,TCS,2.678225e+10,12382622,2162.89
1,1211.29,59.9,1237.0,HCLTECHEQN,1224.0,1162.0,N,5.15,EQ,HCLTECH,1.093562e+10,9028077,1211.29
2,1496.82,47.2,1524.8,TECHMEQN,1502.0,1444.2,N,3.24,EQ,TECHM,3.420341e+09,2285072,1496.82
3,1095.60,34.6,1114.9,INFYEQN,1102.6,1057.1,N,3.24,EQ,INFY,2.300186e+10,20994760,1095.60
4,10268.52,254.0,10442.0,BAJAJ-AUTOEQN,10410.0,10030.5,N,2.50,EQ,BAJAJ-AUTO,1.036336e+10,1009236,10268.52

In [18]:
df3 = pd.merge(df1, df2[['symbol', 'VWAP']], how='left', left_on='symbol', right_on='symbol')

In [20]:
df3.columns

Index(['priority', 'identifier', 'change', 'symbol', 'series', 'marketType',
       'lastPrice', 'totalTradedVolume', 'open', 'dayHigh', 'dayLow',
       'previousClose', 'totalTradedValue', 'yearHigh', 'yearLow', 'ffmc',
       'lastUpdateTime', 'stockIndClosePrice', 'perChange365d', 'perChange30d',
       'date365dAgo', 'date30dAgo', 'nearWKH', 'nearWKL', 'chart30Path',
       'chart365Path', 'companyName', 'pChange', 'VWAP'],
      dtype='str')

In [19]:
df3.head(5)

,priority,identifier,change,symbol,series,marketType,lastPrice,totalTradedVolume,open,dayHigh,...,perChange30d,date365dAgo,date30dAgo,nearWKH,nearWKL,chart30Path,chart365Path,companyName,pChange,VWAP
0,1,NIFTY 50,4.10,NIFTY 50,NaN,NaN,24211.0,322678968,24039.4,24259.80,...,2.49,11-Jul-2025,12-Jun-2026,8.198474,-9.144350,,,NaN,0.02,NaN
1,0,TCSEQN,113.90,TCS,EQ,N,2182.9,12382622,2075.0,2204.90,...,0.99,11-Jul-2025,12-Jun-2026,35.778170,-10.425941,NaN,NaN,TATA CONSULTANCY SERVICES LIMITED,5.51,2162.89
2,0,INFYEQN,34.60,INFY,EQ,N,1102.6,20994760,1057.1,1114.90,...,-1.24,11-Jul-2025,12-Jun-2026,36.192130,-12.235342,NaN,NaN,INFOSYS LIMITED,3.24,1095.60
3,0,HDFCBANKEQN,-7.45,HDFCBANK,EQ,N,817.5,21741736,817.0,821.95,...,5.83,11-Jul-2025,12-Jun-2026,19.892210,-12.502580,NaN,NaN,HDFC BANK LIMITED,-0.90,817.72
4,0,BHARTIARTLEQN,-16.80,BHARTIARTL,EQ,N,1903.6,7862506,1914.0,1917.00,...,4.45,11-Jul-2025,12-Jun-2026,12.458036,-9.370870,NaN,NaN,BHARTI AIRTEL LIMITED,-0.87,1905.40